version: "3"

services:
  mysql:
    build: "./mysql"
    #image: mysql:latest
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "127.0.0.1:13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "verysecurerootpasswordiclassTECHtessolution12345672019docker"
    #volumes:
    #  - ./mysql:/docker-entrypoint-initdb.d
  pma:
    image: "phpmyadmin/phpmyadmin:latest"
    ports:
      - "127.0.0.1:18080:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "verysecurerootpasswordiclassTECHtessolution12345672019docker"
